NOLIST
; Music header
; $VER 1.6

LET MUSIC_HEADER_LENGTH = 35

MUSIC_BEGIN	equ music_adr-MUSIC_HEADER_LENGTH

LIST
	org MUSIC_BEGIN
NOLIST

	dw MUSIC_BEGIN
	dw music_adr
	dw init_music
	dw MUSIC_INIT
	db FIRST_THEME
	db LAST_THEME
	dw play_music
	dw MUSIC_PLAY
	dw music_end
	dw stop_music
	dw music_info
	db MUSIC_DATE_RIP_DAY
	db MUSIC_DATE_RIP_MONTH
LET MUSIC_DATE_RIP_CENTURY = MUSIC_DATE_RIP_YEAR/100
LET MUSIC_DATE_RIP_CALC = MUSIC_DATE_RIP_CENTURY*100
	db MUSIC_DATE_RIP_CENTURY
	db MUSIC_DATE_RIP_YEAR-MUSIC_DATE_RIP_CALC
	db NEED_SYSTEM_VECTOR
	db "Megachur"
	dw EOF_LENGTH
